# Generated by Django 6.0.3 on 2026-03-16 21:30

import catalog.models
import django.db.models.deletion
import django.utils.timezone
import modelcluster.contrib.taggit
import modelcluster.fields
import paradedb.indexes
from django.db import migrations, models


LICENSE_TYPE_SEED_DATA = [
    {
        'slug': 'cc-zero',
        'title': 'Creative Commons CC0 1.0 Universal',
        'code': 'CC0 1.0',
        'description': 'CC0 enables scientists, educators, artists and other creators and owners of copyright- or database-protected content to waive those interests in their works and thereby place them as completely as possible in the public domain, so that others may freely build upon, enhance and reuse the works for any purposes without restriction under copyright or database law.',
        'url': 'https://creativecommons.org/publicdomain/zero/1.0/',
        'is_open': True,
    },
    {
        'slug': 'cc-by-4-0',
        'title': 'Creative Commons Attribution 4.0 International',
        'code': 'CC-BY 4.0',
        'description': 'This license requires that reusers give credit to the creator. It allows reusers to distribute, remix, adapt, and build upon the material in any medium or format, even for commercial purposes.',
        'url': 'https://creativecommons.org/licenses/by/4.0/',
        'is_open': True,
    },
    {
        'slug': 'cc-by-sa-4-0',
        'title': 'Creative Commons Attribution-ShareAlike 4.0 International',
        'code': 'CC-BY-SA 4.0',
        'description': 'This license requires that reusers give credit to the creator. It allows reusers to distribute, remix, adapt, and build upon the material in any medium or format, even for commercial purposes. If others remix, adapt, or build upon the material, they must license the modified material under identical terms.',
        'url': 'https://creativecommons.org/licenses/by-sa/4.0/',
        'is_open': True,
    },
    {
        'slug': 'cc-by-nc-4-0',
        'title': 'Creative Commons Attribution-NonCommercial 4.0 International',
        'code': 'CC-BY-NC 4.0',
        'description': 'This license requires that reusers give credit to the creator. It allows reusers to distribute, remix, adapt, and build upon the material in any medium or format, for noncommercial purposes only.',
        'url': 'https://creativecommons.org/licenses/by-nc/4.0/',
        'is_open': True,
    },
    {
        'slug': 'cc-by-nc-sa-4-0',
        'title': 'Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International',
        'code': 'CC BY-NC-SA 4.0',
        'description': 'This license requires that reusers give credit to the creator. It allows reusers to distribute, remix, adapt, and build upon the material in any medium or format, for noncommercial purposes only. If others modify or adapt the material, they must license the modified material under identical terms.',
        'url': 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
        'is_open': True,
    },
    {
        'slug': 'proprietary',
        'title': 'Proprietary',
        'code': 'PROP',
        'description': 'Proprietary license with restrictions defined by the data owner.',
        'url': '',
        'is_open': False,
    },
]


def seed_license_types(apps, schema_editor):
    LicenseType = apps.get_model('catalog', 'LicenseType')
    for entry in LICENSE_TYPE_SEED_DATA:
        LicenseType.objects.update_or_create(
            slug=entry['slug'],
            defaults={
                'title': entry['title'],
                'code': entry['code'],
                'description': entry['description'],
                'url': entry['url'],
                'is_open': entry['is_open'],
            },
        )


def unseed_license_types(apps, schema_editor):
    LicenseType = apps.get_model('catalog', 'LicenseType')
    LicenseType.objects.filter(
        slug__in=[entry['slug'] for entry in LICENSE_TYPE_SEED_DATA]
    ).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'dataset tag',
                'verbose_name_plural': 'dataset tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('is_open', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_unpublished_changes', models.BooleanField(default=False, editable=False, verbose_name='has unpublished changes')),
                ('first_published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at')),
                ('last_published_at', models.DateTimeField(editable=False, null=True, verbose_name='last published at')),
                ('go_live_at', models.DateTimeField(blank=True, null=True, verbose_name='go live date/time')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time')),
                ('expired', models.BooleanField(default=False, editable=False, verbose_name='expired')),
                ('live', models.BooleanField(default=False, editable=False, verbose_name='live')),
                ('creation_date', models.DateField(default=django.utils.timezone.localdate, editable=False)),
                ('publish_date', models.DateField(blank=True, editable=False, null=True)),
                ('update_date', models.DateField(default=django.utils.timezone.localdate, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('source', models.TextField(blank=True)),
                ('type', models.TextField(blank=True)),
                ('coverage', models.TextField(blank=True)),
                ('author', models.TextField(blank=True)),
                ('editor', models.TextField(blank=True)),
                ('other_colabs', models.TextField(blank=True)),
                ('language', models.TextField(blank=True)),
                ('update_frequency', models.CharField(choices=[('as_needed', 'As needed'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annually', 'Annually'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('live_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='live revision')),
            ],
            options={
                'ordering': ['title'],
                'permissions': [('publish_dataset', 'Can publish/unpublish dataset'), ('manage_dataset_permissions', 'Can manage dataset permissions')],
            },
        ),
        migrations.CreateModel(
            name='DatasetTaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='catalog.dataset')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='catalog.datasettag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dataset',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='catalog.DatasetTaggedItem', to='catalog.DatasetTag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='catalog.licensetype'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='catalog.organization'),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('resource_kind', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('tabular', 'Tabular'), ('spatial', 'Spatial'), ('api', 'API')], default='document', max_length=16)),
                ('storage_kind', models.CharField(choices=[('default', 'Default'), ('default_postgres', 'Default + Postgres')], default='default', max_length=16)),
                ('media_type', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('published', models.BooleanField(default=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('processing_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('dataset', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='catalog.dataset')),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
            ],
            options={
                'ordering': ['dataset__title', 'title'],
                'permissions': [('publish_resource', 'Can publish/unpublish resource'), ('manage_resource_permissions', 'Can manage resource permissions')],
            },
        ),
        migrations.CreateModel(
            name='ResourceAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField()),
                ('spec_type', models.CharField(choices=[('openapi', 'OpenAPI'), ('ogc_api', 'OGC API'), ('wms', 'WMS'), ('wfs', 'WFS'), ('other', 'Other')], default='openapi', max_length=32)),
                ('spec_url', models.URLField(blank=True)),
                ('auth_type', models.CharField(choices=[('none', 'None'), ('api_key', 'API key'), ('bearer', 'Bearer'), ('basic', 'Basic'), ('oauth2', 'OAuth2')], default='none', max_length=16)),
                ('extra_config', models.JSONField(blank=True, default=dict)),
                ('resource', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_items', to='catalog.resource')),
            ],
            options={
                'ordering': ['resource__title'],
            },
        ),
        migrations.CreateModel(
            name='ResourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_resource_files', to='wagtaildocs.document')),
                ('resource', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_items', to='catalog.resource')),
            ],
            options={
                'ordering': ['resource__title'],
            },
        ),
        migrations.CreateModel(
            name='ResourceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(blank=True, max_length=255)),
                ('schema_name', models.CharField(default=catalog.models._default_resource_data_schema, max_length=128)),
                ('table_name', models.CharField(max_length=255)),
                ('primary_key', models.CharField(default='id', max_length=128)),
                ('geometry_field', models.CharField(blank=True, max_length=128)),
                ('srid', models.PositiveIntegerField(blank=True, null=True)),
                ('row_count', models.BigIntegerField(default=0)),
                ('bbox', models.JSONField(blank=True, default=list)),
                ('ogc_api_enabled', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('resource', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='catalog.resource')),
            ],
            options={
                'ordering': ['resource__title', 'layer_name', 'table_name'],
            },
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=paradedb.indexes.BM25Index(fields={'author': {'tokenizer': 'unicode_words'}, 'coverage': {'tokenizer': 'unicode_words'}, 'description': {'tokenizer': 'unicode_words'}, 'editor': {'tokenizer': 'unicode_words'}, 'id': {}, 'language': {'tokenizer': 'unicode_words'}, 'other_colabs': {'tokenizer': 'unicode_words'}, 'source': {'tokenizer': 'unicode_words'}, 'title': {'tokenizer': 'unicode_words'}, 'type': {'tokenizer': 'unicode_words'}}, key_field='id', name='dataset_search_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=paradedb.indexes.BM25Index(fields={'description': {'tokenizer': 'unicode_words'}, 'id': {}, 'media_type': {'tokenizer': 'unicode_words'}, 'metadata': {}, 'title': {'tokenizer': 'unicode_words'}}, key_field='id', name='resource_search_idx'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(fields=('dataset', 'slug'), name='catalog_resource_dataset_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='resourcetable',
            constraint=models.UniqueConstraint(fields=('resource', 'schema_name', 'table_name'), name='catalog_resource_table_unique'),
        ),
        migrations.RunPython(seed_license_types, unseed_license_types),
    ]
